nodeLinker: node-modules

npmRegistryServer: https://registry.npmjs.org

yarnPath: .yarn/releases/yarn-4.0.0-rc.36.cjs

npmScopes:
  webex-connect:
    npmAlwaysAuth: true
    npmAuthToken: ${CONNECT_TOKEN}
    npmRegistryServer: https://registry.npmjs.org
