#!/usr/bin/groovy

// Node label
// Find more info about these:
// https://engit.cisco.com/build/cloudbees-jenkins/documentation-central-jenkins-build-agents
def NODE_LABEL = 'docker'
def DOCKER_REGISTRY = '527856644868.dkr.ecr.us-east-2.amazonaws.com'
def DOCKER_REPO = 'cpaas'
def DOCKER_IMAGE = 'webrtc-core'
def DOCKER_TEST_IMAGE = 'webrtc-core-test'
def DOCKER_TAG  // Computed later
def AWS_CREDS_ID = 'ecr:us-east-2:cpaas-aws-creds' // this uses cpaas-aws-creds from Jenkins

pipeline {
  agent any

  tools {nodejs "Node v14"}

  options {
    ansiColor('xterm')
  }

  stages {
    stage('Prerequisite Check') {
      steps {
        sh 'node -v'
        sh 'npm -v'
        sh 'npm install yarn'
        sh 'pwd'
        echo "${env.WORKSPACE}"
        echo "${env.includeCoverage}"
      }
    }
    stage('Install dependencies') {
      steps {
        sh './node_modules/yarn/bin/yarn install'
      }
    }
    stage('Validate Lint') {
      steps {
        // Validate lint
        sh './node_modules/yarn/bin/yarn test:lint'
        //@TODO: handle lint errors (fail build??)
      }
    }
    stage('Run unit test') {
        // Run unit test
        if (env.includeCoverage == true) {
          sh './node_modules/yarn/bin/yarn test:unit --coverage'
          // publish report
          publishHTML([allowMissing: false,
                       alwaysLinkToLastBuild: false,
                       keepAll: true,
                       reportDir: 'coverage/lcov-report',
                       reportFiles: 'index.html',
                       reportName: 'HTML Report',
                       reportTitles: 'All Tests'])
        } else {
          // Run tests without coverage
          sh './node_modules/yarn/bin/yarn test:unit'
        }
    }
    stage('Build package') {
      steps {
        sh './node_modules/yarn/bin/yarn build'
      }
    }
//    stage('Publish to artifactory') {
//      if (env.BRANCH_NAME == "master") {
//          steps {
//            sh 'npm publish'
//        }
//      }
//      else {
//        echo "Skipping publish - This build is not occurring on a publish-able branch!"
//      }
//    }

  }
}
